name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
  pull_request:
    branches:
      - main
  shchedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "🎉 The job was triggered by event: ${{ github.event_name }}"
         echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."
         
      - uses: actions/checkout@v4.1

      - run: tree
    
